version: 2
updates:
  - package-ecosystem: rust-toolchain
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
      timezone: America/New_York
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '08:00'
      timezone: America/New_York
