# output_file: events.log
# batch_size: 10  # Number of events to fetch per batch (default: 10)
channels:
  - Application
  - System
  - Security # Requires elevated privileges
  # - Microsoft-Windows-PowerShell/Operational
